name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Lint the code
        run: biome lint ./packages/nestjs-environment-variables-provider
  
  format:
    name: Code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run formatting
        run: biome format ./packages/nestjs-environment-variables-provider --write

  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Check dist folder
        run: |
          if [ ! -d "packages/nestjs-environment-variables-provider/dist" ]; then
            echo "dist folder is missing"
            exit 1
          fi
          if [ ! -f "packages/nestjs-environment-variables-provider/dist/esm/index.js" ]; then
            echo "ESM build is missing"
            exit 1
          fi
          if [ ! -f "packages/nestjs-environment-variables-provider/dist/cjs/index.js" ]; then
            echo "CJS build is missing"
            exit 1
          fi

  test:
    name: Run tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  version-compatibility:
    name: NestJS Version Compatibility
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nestjs-version: ['11.x']
        nestjs-config-version: ['4.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install specific NestJS version
        run: |
          npm install --save-peer @nestjs/common@${{ matrix.nestjs-version }} @nestjs/core@${{ matrix.nestjs-version }} @nestjs/config@${{ matrix.nestjs-config-version }}

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm run test
