name: Publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@otakusan76'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build -w packages/nestjs-environment-variables-provider

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/nestjs-environment-variables-provider
          if [ ${{ github.event.release.prerelease }} == true ]; then
            npm publish --tag next --provenance --access public
          else
            npm publish --tag latest --provenance --access public
          fi