name: Publish

on:
  release:
    types: [published]

env:
  HUSKY: 0

permissions:
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Publish with latest tag
        if: github.event.release.prerelease == false
        run: npm publish --tag latest --provenance
        working-directory: packages/nestjs-environment-variables-provider
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish with next tag
        if: github.event.release.prerelease == true
        run: npm publish --tag next --provenance
        working-directory: packages/nestjs-environment-variables-provider
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}